### PR TITLE
docs: Add quick start examples

### PR DESCRIPTION
**Pull request by adigitoleo**
Adds two quick start examples, one for “normal” plots and one for a map.
Maybe the map example can be improved a bit later.

### CODE REVIEW

**Comment by adigitoleo** [comment]
Had to use the `gmtend(show = true)` to avoid missing output file errors [like this one](https://joa-quim.github.io/GMTjl_doc/examples/plotting_functions/01_lines/#the_snake_skier) when testing locally, maybe this can be avoided?

**Comment by adigitoleo** [comment]
Hmm, `subplot(:end)` followed by `gmtend(show = true)` produces the missing file error, this was not happening without `subplot(:end)`.

Edit: I'm just removing the `gmtbegin/gmtend`, it works fine without it.

With current GMT.jl master there seems to be a problem with the `region = :global` in the map inset.

**Comment by adigitoleo** [comment]
quickstart1
quickstart2

**Comment by joa-quim** [comment]
Ok, thanks for the examples and sorry for the lack of information. Some points:

- The Docs repository is now in https://github.com/GenericMappingTools/GMTjl_doc
- The subplot examples must go to https://github.com/GenericMappingTools/GMTjl_doc/tree/master/examples/subplot
- and the inset to https://github.com/GenericMappingTools/GMTjl_doc/tree/master/examples/embellish (I'll put one other example there)

**Comment by joa-quim** [comment]
> With current GMT.jl master there seems to be a problem with the region = :global in the map inset.

Not, you need to end the inset with a ``inset(:end)``

**Comment by adigitoleo** [comment]
Thanks for the info, I'll move it across. Not sure why the manifest file got commited, that was a mistake.

I was thinking that maybe it could be helpful to have a quick example right away on the front page, what do you think? I can move these to the other sections if you want, maybe there is a better example for the homepage?

**Comment by joa-quim** [comment]
With the examples tiles so visible in the main page I prefer not to have any quick first plot in the front page.

**Pull request closed without merging**
